version: '3'

services:

  master:
    hostname: postgresql-0
    image: centerforopenscience/postgres:9.6-repmgr
    command:
      - /bin/bash
      - -c
      - chmod 550 /entrypoint.sh && /usr/bin/supervisord
    env_file:
      - docker-compose.env
    environment:
      POD_IP: 172.8.0.1
      POD_NAME: postgresql-0
    volumes:
      - ./config/entrypoint.sh:/entrypoint.sh
      - ./config/repmgr.conf:/etc/_repmgr.conf
      - ./config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - '5432:5432'
    networks:
      overlay:
        aliases:
          - postgresql-0
          - postgresql
          - postgres

  standby:
    hostname: postgresql-1
    image: centerforopenscience/postgres:9.6-repmgr
    command:
      - /bin/bash
      - -c
      - chmod 550 /entrypoint.sh && /usr/bin/supervisord
    env_file:
      - docker-compose.env
    environment:
      POD_IP: 172.8.0.2
      POD_NAME: postgresql-1
    volumes:
      - ./config/entrypoint.sh:/entrypoint.sh
      - ./config/repmgr.conf:/etc/_repmgr.conf
      - ./config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      overlay:
        aliases:
          - standby

  barman:
    hostname: barman
    image: centerforopenscience/barman:9.6
    env_file:
      - docker-compose.env
    environment:
      POD_IP: 172.8.0.3
      POD_NAME: barman-498932869-1bcxy
    volumes:
      - ./config/barman-db.conf:/etc/barman.d/barman-db.conf
    networks:
      overlay:
        aliases:
          - barman

networks:
  overlay:
    driver: bridge
